# Generated by Django 4.2.6 on 2023-11-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_post_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='team',
        ),
    ]
