# Generated by Django 4.2.6 on 2023-11-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member',
            field=models.CharField(max_length=1000),
        ),
    ]
