# Generated by Django 4.2.6 on 2023-11-03 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='member',
            field=models.TextField(default='YourDefaultValueHere'),
        ),
    ]
