# Generated by Django 4.2.6 on 2023-11-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_team_pub_date_alter_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(default='YourDefaultValueHere'),
        ),
    ]
