# Generated by Django 4.2.6 on 2024-01-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_post_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('S', '小'), ('M', '中'), ('L', '大')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('一般書籍', '一般書籍'), ('教學用書', '教學用書')], default='一般書籍', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='is_borrowed',
            field=models.BooleanField(default=False, verbose_name='外借中'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_link',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(default='不詳', max_length=50),
        ),
    ]
