# Generated by Django 4.2.6 on 2024-01-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_product_post_category_post_is_borrowed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_link',
        ),
        migrations.AddField(
            model_name='post',
            name='photolink',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1),
        ),
    ]
